### ISSUE TITLE
Many thumbnails are pixelated

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#1]
See for example, the image here: http://wikiedu.org/blog/2015/04/10/arizona-geoclub-wikipedia/

See also the About Us profiles: http://wikiedu.org/about-us/

**Comment by dmak78** [comment]
@ragesoss This should be fixed now. Needed to up the resolution settings on the Team Manager thumbnails. The images in the post were being stretch to 100% of the post container, to fix this I just set MAX width instead, so they should display as intended now.

**Comment by ragesoss** [comment]
Nice. Thanks @dmak78 !
