### ISSUE TITLE
Copy adjustments for brochure pages

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#19]
Quantitative:
- Move "Students change." from the first paragraph to the second.
- Remove "Inspiring Learning" from the end of the second paragraph.
- Change (red) "Since 2010, students have made amazing contributions to Wikipedia" to "Measuring the difference"
- Remove all the red overline descriptions of the numbers. Following the designs of the print versions, we want to lead with the numbers and explain them after.
- For the "Courses taught..." and "Number of students...", add in copy from the brochure beneath the numbers: "The number of courses taught throughout our program since 2010." and "That's how many students have taken on Wikipedia assignments since 2010."

Qualitative:
- Remove all the red overline descriptions of the numbers (per above).
- "Thoughts from Students" works; we can make that black.

**Comment by ragesoss** [comment]
Actually, on further reflection, we want to remove both the "Thoughts from Students" and "Thoughts from Instructors" headers. The quotes explicitly identify the people as instructor or student, so it shouldn't be a source of confusion.

**Comment by thenickcox** [comment]
Hi, @ragesoss. One issue with the photos of the students is that they don't go super well together, even with a higher-res version of Anna:

![screen shot 2015-07-15 at 12 41 50 pm](https://cloud.githubusercontent.com/assets/702327/8708111/f1f743f0-2aee-11e5-82f7-ff3a2b3bd0cd.png)

The coloring is quite different; we could make them both black & white to make them look less visually jarring. Or we could keep them as-is. Thoughts?

**Comment by thenickcox** [comment]
Lastly, one final copy edit is needed. On the "How do you measure the difference that open knowledge makes?" page, there's a heading that says, "Since 2010, students have made amazing contributions to Wikipedia." You can see it in context here:

![screen shot 2015-07-15 at 12 44 49 pm](https://cloud.githubusercontent.com/assets/702327/8708180/5638ed8c-2aef-11e5-88b6-ac0da1adf58f.png)

Is there final copy for that bit?

**Comment by ragesoss** [comment]
That red copy should be changed to "Measuring the difference".

**Comment by thenickcox** [comment]
Right you are! Missed that in your edits. Sorry.

**Comment by ragesoss** [comment]
Thanks Nick.

We agree that this doesn't work with the photos we have. Can you explore
doing it without photos at all for these quotes (and then at a later date,
we can add new photo/quote pairs when we have good ones).

-Sage

**Comment by ragesoss** [comment]
@thenickcox I think this works, for now (until we find some better pictures). One little issue is that only three of the quotes are displayed in the mobile view. The final one just disappears, and isn't available in the swipe segment.
