### ISSUE TITLE
Smiley face appears in the footer

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#26]
There's a little smiley gif that appears (if you're not logged in) in the footer. These needs to disappear, ideally without killing the wpstats functionality that (I think) is what inserts it.

**Comment by thenickcox** [comment]
Turns out this was a setting in Jetpack. Just disabled it. Should still be tracking.

![screen shot 2015-07-24 at 1 18 05 pm](https://cloud.githubusercontent.com/assets/702327/8883815/a99129ea-3206-11e5-9bd1-0e1fcdb4e45c.png)

(Which begs the question, why would that be a setting? But I digress.)

**Comment by ragesoss** [comment]
And why would it be enabled by default?

/me shakes head

**Comment by thenickcox** [comment]
Worse yet, the fact that it says it _should_ still work when hidden…

Is there someone in your organization responsible for tracking those stats? I would want to make sure that it does still work, given that it "should".
