### ISSUE TITLE
Contact forms are not working

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#28]
We discovered today that the contact forms have not been working. :-/

**Comment by mattfordham** [comment]
It looks like this was sending to Kevin's email address, which I have been receiving. I just got the test Adam sent, but havn't seen any other messages come through. We'll get this fixed ASAP.

**Comment by mattfordham** [comment]
I take that back, I found about 10 messages in my spam folder I'll send them along.

**Comment by ragesoss** [comment]
Ah. There should have been some others from earlier days/weeks. Could you
search your email for them and pass them along?

**Comment by mattfordham** [comment]
So, the feedback form tool will notify the author of the page/post that the form is on. I changed this author to you (@ragesoss), so you should be notified. I believe Kevin assumed all users were notified. 

Regardless of notifications, all of the "feedback" is collected and visible here: http://wikiedu.org/wp-admin/edit.php?post_type=feedback

**Comment by ragesoss** [comment]
We aren't able to receive any email, even after setting the author to the appropriate person.

**Comment by mattfordham** [comment]
Hmm, odd. I'll investigate.

**Comment by mattfordham** [comment]
I just made myself the author and tested... it worked as expected. The email associated with your account is sage@wikiedu.org. Is that correct? Also, perhaps try sending a message from a different email address, not on the wikiedu.org domain, sometimes servers are funny about sending to their own domains.

**Comment by ragesoss** [comment]
It looks like it only works when we use email addresses that are not @wikiedu.org (or @wikiedfoundation.org). So, a server/email problem, probably the same one that keeps our office wiki from sending mail.

**Comment by mattfordham** [comment]
This likely has to do with sendmail configuration on the server. We'll tweak around on the server a bit tomorrow. This is the likely solution: http://serverfault.com/a/128450

**Comment by mattfordham** [comment]
@ragesoss I don't believe I have SSH access to the wikiedu.org server (or perhaps something changed about it). Perhaps you could hook me up via email?

**Comment by ragesoss** [comment]
Matt, send me your pub key.

**Comment by mattfordham** [comment]
After being reminded that cPanel is in the picture, I believe my changing of the setting in the screenshot should have fixed the issue. Could you confirm?

<img width="1250" alt="screen shot 2015-08-31 at 9 38 00 am" src="https://cloud.githubusercontent.com/assets/292703/9584093/00ec2188-4fc4-11e5-9a2d-a38f6c1b494b.png">

**Comment by mattfordham** [comment]
And I believe you are not hosting your wikiedu.org email on the server... tell me if I was incorrect.

**Comment by ragesoss** [comment]
Yes, it works! And that's correct, our email is handled by Google Apps.

**Comment by mattfordham** [comment]
Woohoo!!! :)
