### ISSUE TITLE
Menu is not available in mobile view

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#4]
There's no way to navigate to key pages such as For-Instructors on mobile.

Also, the logo does not link to the homepage in mobile view (as it does in desktop view).

**Comment by dmak78** [comment]
@ragesoss in progress

**Comment by dmak78** [comment]
@ragesoss Got the mobile nav in there now. Currently clicking the logo shows the menu. This may not the most obvious so may switch it out for a menu icon, but in the meantime didnt want to remove the Wikiedu logo from the mobile view just for a nav icon, but that may be the solution we go with.

**Comment by ragesoss** [comment]
This is excellent, thanks!
