### ISSUE TITLE
Title styling needs to be able to work well with bright images and long titles

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#40]
We constantly have to work around issues like this.

![bad](https://cloud.githubusercontent.com/assets/848483/24053200/7b92a5d6-0af5-11e7-9200-b8a37b58e9f4.png)

**Comment by abhay313** [comment]
Can I take this issue ?

**Comment by hanishtharwani123** [comment]
can you assign this issue to me

**Comment by hanishtharwani123** [comment]
@ragesoss

**Comment by ragesoss** [comment]
We no longer use this theme. I should archive it.
